[package]
name = "blastfile"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = ["full"] }
regex = "1.11.2"
axum = "0.8.4"
tower-http = { version = "0.6.6", features = ["fs", "trace"] }
futures-util = "0.3.31"